// @generated by `cargo xtask generate`; do not edit by hand.
import { invoke } from "@tauri-apps/api/core";

export interface FoundationStatus {
  readonly capability: "phase_00_foundation";
  readonly schemaVersion: 1;
}

export async function getFoundationStatus(): Promise<FoundationStatus> {
  return invoke<FoundationStatus>("app_get_foundation_status");
}
