packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  edgedriver: false
  esbuild: false
  geckodriver: false

supportedArchitectures:
  os:
    - linux
    - darwin
    - win32
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
