// SPDX-License-Identifier: Apache-2.0
// @generated by `cargo xtask generate` from schemas/domain-packs/official-test.contract.json; do not edit.
// source-blake3: 9101d652e87746340573cedc279f834eb861316a093531817cced2f2e32d8130

pub const OFFICIAL_TEST_PACK_ID: &str = "official.test";
pub const OFFICIAL_TEST_PACK_VERSION: &str = "0.1.0";
pub const OFFICIAL_TEST_PACK_CONTRACT_JSON: &str = r#"{
  "aiTools": [
    {
      "commandId": "official.test.configure_entity",
      "description": "Configure one synthetic contract entity with bounded values.",
      "name": "configure_test_entity"
    }
  ],
  "commands": [
    {
      "aiGroupingAllowed": true,
      "changeSchema": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": false,
        "properties": {
          "after": {},
          "before": {},
          "path": {
            "pattern": "^/domain/entities/",
            "type": "string"
          }
        },
        "required": [
          "path",
          "before",
          "after"
        ],
        "type": "object"
      },
      "description": {
        "defaultText": "Sets the bounded Boolean and integer values used by the contract fixture.",
        "key": "official.test.command.configure_entity.description"
      },
      "id": "official.test.configure_entity",
      "invalidExamples": [
        {
          "enabled": true,
          "entityId": "not-a-uuid",
          "target": 11
        }
      ],
      "payloadSchema": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": false,
        "properties": {
          "enabled": {
            "type": "boolean"
          },
          "entityId": {
            "format": "uuid",
            "type": "string"
          },
          "target": {
            "maximum": 10,
            "minimum": 0,
            "type": "integer"
          }
        },
        "required": [
          "entityId",
          "enabled",
          "target"
        ],
        "type": "object"
      },
      "resultSchema": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": false,
        "properties": {
          "entityId": {
            "format": "uuid",
            "type": "string"
          }
        },
        "required": [
          "entityId"
        ],
        "type": "object"
      },
      "reversibility": "inverseCommand",
      "risk": "ordinaryMutation",
      "title": {
        "defaultText": "Configure test entity",
        "key": "official.test.command.configure_entity.title"
      },
      "validExamples": [
        {
          "enabled": true,
          "entityId": "018f25a7-8b3c-7d11-8000-000000000001",
          "target": 3
        }
      ]
    }
  ],
  "pack": {
    "id": "official.test",
    "latestSchemaVersion": 1,
    "packVersion": "0.1.0",
    "portableSchemaVersion": 2,
    "shareResultSchemaVersion": 1
  },
  "portableSchema": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
      "entities": {
        "additionalProperties": {
          "type": "object"
        },
        "type": "object"
      },
      "extensions": {
        "type": "object"
      },
      "lockedAssignments": {
        "additionalProperties": {
          "type": "object"
        },
        "type": "object"
      },
      "preferences": {
        "additionalProperties": {
          "type": "object"
        },
        "type": "object"
      },
      "rules": {
        "additionalProperties": {
          "type": "object"
        },
        "type": "object"
      },
      "schemaVersion": {
        "const": 2
      }
    },
    "required": [
      "schemaVersion",
      "entities",
      "rules",
      "preferences",
      "lockedAssignments",
      "extensions"
    ],
    "type": "object"
  },
  "schemaVersion": 1,
  "shareResultSchema": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
      "assignments": {
        "items": {
          "additionalProperties": false,
          "properties": {
            "assignmentId": {
              "type": "string"
            },
            "value": {
              "oneOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "integer"
                },
                {
                  "type": "null"
                }
              ]
            }
          },
          "required": [
            "assignmentId",
            "value"
          ],
          "type": "object"
        },
        "type": "array"
      },
      "schemaVersion": {
        "const": 1
      }
    },
    "required": [
      "schemaVersion",
      "assignments"
    ],
    "type": "object"
  },
  "uiManifest": {
    "entityKinds": [
      {
        "id": "official.test.entity",
        "titleKey": "official.test.entity.title"
      }
    ],
    "exporters": [
      {
        "id": "official.test.export.portable-v2",
        "titleKey": "official.test.export.title"
      }
    ],
    "importers": [
      {
        "id": "official.test.import.portable-v2",
        "titleKey": "official.test.import.title"
      }
    ],
    "resultViews": [
      {
        "id": "official.test.result.summary",
        "titleKey": "official.test.result.summary.title"
      }
    ],
    "ruleKinds": [
      {
        "id": "official.test.required-target",
        "titleKey": "official.test.rule.required_target.title"
      }
    ],
    "setupSteps": [
      {
        "id": "official.test.setup.entity",
        "titleKey": "official.test.setup.entity.title"
      }
    ]
  }
}
"#;
pub const OFFICIAL_TEST_COMMAND_IDS: &[&str] = &["official.test.configure_entity"];
