use std::fs;
use std::path::Path;

use anyhow::{Context, Result, bail, ensure};

const GENERATED_DESKTOP_API_PATH: &str = "apps/desktop/src/api/generated.ts";
const GENERATED_RUST_COMMAND_CATALOG_PATH: &str =
    "apps/desktop/src-tauri/src/generated_command_catalog.rs";
const TYPESCRIPT_COMMAND_CATALOG_PLACEHOLDER: &str = "__COMMAND_CATALOG__";

const COMMAND_CATALOG: &[&str] = &[
    "app_get_info",
    "app_get_capabilities",
    "app_get_paths_summary",
    "app_open_data_folder",
    "app_create_support_bundle_preview",
    "app_create_support_bundle",
    "app_check_for_update",
    "app_install_update",
    "app_get_license_inventory",
    "pack_list",
    "pack_describe",
    "solver_list",
    "solver_describe",
    "solver_get_support_matrix",
    "solver_get_deferred_gates",
    "project_list",
    "project_get_metadata",
    "project_create",
    "project_duplicate",
    "project_archive",
    "project_unarchive",
    "project_delete",
    "project_import_preview",
    "project_import_apply",
    "project_export_preview",
    "project_export_create",
    "project_backup_preview",
    "project_backup_create",
    "project_restore_preview",
    "project_restore_apply",
    "project_operation_cancel",
    "project_unopened_bundle_inspect",
    "project_unopened_bundle_reexport",
    "scenario_get_summary",
    "scenario_get_setup_status",
    "scenario_get_view",
    "scenario_get_entity",
    "scenario_search_entities",
    "scenario_get_rule_catalog",
    "scenario_get_command_catalog",
    "scenario_apply_command",
    "scenario_apply_batch",
    "scenario_validate",
    "scenario_undo",
    "scenario_redo",
    "scenario_get_history",
    "scenario_migrate_preview",
    "solve_get_backend_options",
    "solve_estimate_model",
    "solve_start",
    "solve_cancel",
    "solve_get_job",
    "solve_list_runs",
    "solve_get_diagnostics_summary",
    "solution_list",
    "solution_get_summary",
    "solution_get_view",
    "solution_select",
    "solution_verify",
    "solution_compare",
    "solution_explain",
    "solution_start_counterfactual",
    "solution_cancel_counterfactual",
    "solution_lock_assignment",
    "solution_unlock_assignment",
    "solution_create_repair_request",
    "solution_export_preview",
    "solution_export",
    "solution_share_preview",
    "solution_share_create",
    "solution_export_cancel",
    "ai_get_provider_catalog",
    "ai_get_configuration",
    "ai_store_credential",
    "ai_delete_credential",
    "ai_test_provider",
    "ai_list_models",
    "ai_list_conversations",
    "ai_create_conversation",
    "ai_get_conversation",
    "ai_send_turn",
    "ai_cancel_turn",
    "ai_get_proposal",
    "ai_apply_proposal",
    "ai_reject_proposal",
    "ai_delete_conversation",
    "settings_get",
    "settings_update",
    "settings_reset_section",
    "settings_export_nonsecret",
    "settings_import_nonsecret",
];

const DESKTOP_API_TEMPLATE: &str = r#"// @generated by `cargo xtask generate`; do not edit by hand.
import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";

export const API_SCHEMA_VERSION = 1 as const;
export const PROVISIONAL_PORTABLE_EXTENSION = ".eutheto" as const;

export type UuidV7 = string;
export type Revision = number;
export type JsonValue =
  null | boolean | number | string | readonly JsonValue[] | { readonly [key: string]: JsonValue };

export type ResourceRef =
  | { readonly type: "scenario"; readonly id: UuidV7 }
  | { readonly type: "person"; readonly id: UuidV7 }
  | { readonly type: "rule"; readonly id: UuidV7 }
  | { readonly type: "assignment"; readonly id: UuidV7 }
  | { readonly type: "solveRun"; readonly id: UuidV7 }
  | { readonly type: "solution"; readonly id: UuidV7 }
  | { readonly type: "pack"; readonly id: string }
  | { readonly type: "backend"; readonly id: string };
export type ProjectScope = "active" | "archived" | "all";
export type UnitSystem = "metric" | "us-customary";
export type GapPolicy = "reject" | "moveForward" | "packDefined";
export type OverlapPolicy = "earlier" | "later" | "reject";
export type RestoreMode = "import-scenario" | "add-backup" | "replace-library";
export type CollisionAction = "create-copy" | "replace" | "skip";
export type SupplementalCollisionAction = "replace" | "skip";
export type SupplementalSectionKind = "results" | "shared-records" | "preferences" | "assets";
export type PortableBackupAssetSelection = "all" | "exclude-all" | "v1-threshold";
export type BackupSelectionScope = "scenario" | "library";
export type OmittedAssetReason = "exclude-all" | "above-v1-threshold" | "import-excluded";
export type FixedExclusion =
  | "local-undo-and-audit-history"
  | "sqlite-and-database-internals"
  | "credentials-tokens-and-keychain-references"
  | "device-local-paths-and-window-state"
  | "logs-caches-and-temporary-data"
  | "redistribution-prohibited-provider-data"
  | "executable-content";
export type ValidationSeverity = "info" | "warning" | "error";
export type ApiErrorCategory =
  | "validation"
  | "conflict"
  | "notFound"
  | "unsupported"
  | "solver"
  | "verification"
  | "storage"
  | "protocol"
  | "ai"
  | "internal";

export interface ValidationIssue {
  readonly code: string;
  readonly severity: ValidationSeverity;
  readonly message: string;
  readonly fieldPath: string | null;
  readonly resource: ResourceRef | null;
}

export interface FieldErrorDto {
  readonly field: string;
  readonly code: string;
  readonly message: string;
}

export type SafeDiagnosticValue =
  | { readonly type: "text"; readonly value: string }
  | { readonly type: "integer"; readonly value: number }
  | { readonly type: "boolean"; readonly value: boolean };

export interface ApiErrorDto {
  readonly code: string;
  readonly message: string;
  readonly category: ApiErrorCategory;
  readonly retryable: boolean;
  readonly fieldErrors: readonly FieldErrorDto[];
  readonly details: Readonly<Record<string, SafeDiagnosticValue>> | null;
  readonly diagnosticId: UuidV7 | null;
}

export interface ApiResponseDto<T> {
  readonly schemaVersion: typeof API_SCHEMA_VERSION;
  readonly requestId: UuidV7;
  readonly currentRevision: Revision | null;
  readonly warnings: readonly ValidationIssue[];
  readonly result: T;
}

export interface FoundationStatus {
  readonly schemaVersion: number;
  readonly capability: string;
}

export interface AppInfoDto {
  readonly name: string;
  readonly version: string;
  readonly foundation: FoundationStatus;
  readonly portableExtension: typeof PROVISIONAL_PORTABLE_EXTENSION;
  readonly portableExtensionStatus: "provisional-development-only";
}

export interface AppCapabilitiesDto {
  readonly availableCommands: readonly CatalogCommand[];
  readonly unavailableCommands: readonly CatalogCommand[];
}

export interface AppPathsSummaryDto {
  readonly appDataConfigured: boolean;
  readonly cacheConfigured: boolean;
  readonly backupConfigured: boolean;
}

export type DirectoryAvailabilityLabel = "available" | "unavailable";

export interface SupportApplicationMetadataDto {
  readonly name: string;
  readonly version: string;
}

export interface SupportSchemaMetadataDto {
  readonly scenarioFormatVersion: number;
  readonly storageSchemaVersion: number;
}

export interface SupportLibraryMetadataDto {
  readonly revision: Revision;
  readonly scenarioCount: number;
  readonly activeSolveRunCount: number;
  readonly interruptedRecoveryCount: number;
}

export interface SupportDirectoryMetadataDto {
  readonly applicationData: DirectoryAvailabilityLabel;
  readonly safetyBackups: DirectoryAvailabilityLabel;
}

export interface SupportPreviewDto {
  readonly schemaVersion: number;
  readonly generatedAt: string;
  readonly application: SupportApplicationMetadataDto;
  readonly schemas: SupportSchemaMetadataDto;
  readonly library: SupportLibraryMetadataDto;
  readonly directories: SupportDirectoryMetadataDto;
}
export interface LocalizedTextDto {
  readonly key: string;
  readonly defaultText: string;
}

export type DomainCapability =
  | "commands"
  | "compilation"
  | "projection"
  | "verification"
  | "scoring"
  | "portableData"
  | "shareResult"
  | "uiManifest"
  | "aiTools";

export type ExplanationCapability =
  | "validation"
  | "infeasibility"
  | "assignment"
  | "counterfactual"
  | "solutionDifference"
  | "repair"
  | "optimalityStatus";

export interface DomainPackDescriptorDto {
  readonly id: string;
  readonly displayName: LocalizedTextDto;
  readonly description: LocalizedTextDto;
  readonly packVersion: string;
  readonly scenarioVersions: {
    readonly latest: number;
    readonly migratableFrom: readonly number[];
  };
  readonly iconId: string;
  readonly capabilities: readonly DomainCapability[];
  readonly explanationCapabilities: readonly ExplanationCapability[];
  readonly portableSchemaVersion: number;
  readonly portableCapabilities: readonly string[];
  readonly shareResultSchemaVersion: number;
  readonly documentationUrl: string | null;
  readonly license: {
    readonly spdxExpression: string;
    readonly attribution: string;
  };
  readonly syntheticTestOnly: boolean;
}

export interface DomainCommandDescriptorDto {
  readonly id: string;
  readonly title: LocalizedTextDto;
  readonly description: LocalizedTextDto;
  readonly risk: "ordinaryMutation" | "destructiveMutation";
  readonly reversibility: "inverseCommand" | "irreversible";
  readonly aiGroupingAllowed: boolean;
  readonly payloadSchema: JsonValue;
  readonly resultSchema: JsonValue;
  readonly changeSchema: JsonValue;
  readonly validExamples: readonly JsonValue[];
  readonly invalidExamples: readonly JsonValue[];
}

export interface DomainKindDescriptorDto {
  readonly id: string;
  readonly title: LocalizedTextDto;
  readonly description: LocalizedTextDto;
}

export interface DomainCatalogDto {
  readonly packId: string;
  readonly scenarioSchemaVersion: number;
  readonly portableSchema: JsonValue;
  readonly shareResultSchema: JsonValue;
  readonly commands: readonly DomainCommandDescriptorDto[];
  readonly aiTools: readonly {
    readonly commandId: string;
    readonly name: string;
    readonly description: string;
    readonly inputSchema: JsonValue;
    readonly validExamples: readonly JsonValue[];
  }[];
  readonly ui: {
    readonly setupSteps: readonly DomainKindDescriptorDto[];
    readonly entityKinds: readonly DomainKindDescriptorDto[];
    readonly ruleKinds: readonly DomainKindDescriptorDto[];
    readonly goalKinds: readonly DomainKindDescriptorDto[];
    readonly scoreKinds: readonly {
      readonly id: string;
      readonly title: LocalizedTextDto;
      readonly minimize: boolean;
    }[];
    readonly provenanceKinds: readonly DomainKindDescriptorDto[];
    readonly resultViews: readonly DomainKindDescriptorDto[];
    readonly importers: readonly {
      readonly id: string;
      readonly title: LocalizedTextDto;
      readonly schemaVersion: number;
    }[];
    readonly exporters: readonly {
      readonly id: string;
      readonly title: LocalizedTextDto;
      readonly schemaVersion: number;
    }[];
  };
}

export interface DomainPackMetadataDto {
  readonly descriptor: DomainPackDescriptorDto;
  readonly catalog: DomainCatalogDto;
}

export interface SolverDescriptorDto {
  readonly id: string;
  readonly displayName: string;
  readonly version: string;
  readonly adapterVersion: string;
  readonly distribution: "builtIn" | "bundledWorker" | "userProvided";
  readonly license: {
    readonly spdxExpression: string;
    readonly licenseName: string;
    readonly sourceUrl: string | null;
  };
  readonly stability: "stable" | "beta" | "experimental";
  readonly capabilities: {
    readonly supported: readonly string[];
    readonly degraded: readonly string[];
  };
}

export type SupportFeatureCategory = "primitive" | "objective" | "projection" | "solve";
export type SupportFeatureGate =
  { readonly kind: "unconditional" } | { readonly kind: "enabled"; readonly gateId: string };

export interface SolverSupportFeatureDto {
  readonly id: string;
  readonly category: SupportFeatureCategory;
  readonly gate: SupportFeatureGate;
}

export type SolverSupportCellDto =
  | {
      readonly featureId: string;
      readonly support: "supported";
      readonly fixtureId: string;
    }
  | {
      readonly featureId: string;
      readonly support: "degraded";
      readonly restrictionId: string;
      readonly reason: string;
      readonly remediation: string;
      readonly fixtureId: string;
    }
  | {
      readonly featureId: string;
      readonly support: "unsupported";
      readonly reason: string;
      readonly remediation: string;
      readonly fixtureId: string;
    };

export interface SolverSupportBackendColumnDto {
  readonly backendId: string;
  readonly backendVersion: string;
  readonly adapterVersion: string;
  readonly cells: readonly SolverSupportCellDto[];
}

export interface SolverSupportMatrixDto {
  readonly schemaVersion: number;
  readonly planningIrSchemaVersion: number;
  readonly features: readonly SolverSupportFeatureDto[];
  readonly productionBackendIds: readonly string[];
  readonly backendColumns: readonly SolverSupportBackendColumnDto[];
}

export interface DeferredSolverGateDto {
  readonly backendId: string;
  readonly candidateVersion: string;
  readonly owningPhase: number;
}

export interface UnopenedBundleMetadataDto {
  readonly fileSha256: string;
  readonly format: string;
  readonly formatVersion: number;
  readonly portableSchemaVersion: number;
  readonly bundleKind: string | null;
  readonly title: string | null;
  readonly requiredCapabilities: readonly PortableCapabilityDto[];
  readonly scenarios: readonly {
    readonly path: string;
    readonly scenarioId: string | null;
    readonly packId: string | null;
    readonly packSchemaVersion: number | null;
  }[];
}

export interface UnopenedBundlePreviewDto {
  readonly previewId: UuidV7;
  readonly metadata: UnopenedBundleMetadataDto;
}

export interface DomainPackRef {
  readonly id: UuidV7;
  readonly schemaVersion: number;
}

export interface Horizon {
  readonly start: string;
  readonly end: string;
}

export interface ScenarioSettings {
  readonly timeZone: string;
  readonly locale: string;
  readonly units: UnitSystem;
  readonly horizon: Horizon;
  readonly gapPolicy: GapPolicy;
  readonly overlapPolicy: OverlapPolicy;
}

export interface ProjectSummaryDto {
  readonly scenarioId: UuidV7;
  readonly title: string;
  readonly domainPackId: UuidV7;
  readonly revision: Revision;
  readonly updatedAt: string;
  readonly archived: boolean;
}

export interface ProjectMetadataDto {
  readonly scenarioId: UuidV7;
  readonly title: string;
  readonly description: string;
  readonly domainPack: DomainPackRef;
  readonly revision: Revision;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly archivedAt: string | null;
}

export interface ImportOptions {
  readonly restoreMode: RestoreMode;
  readonly includeResults: boolean;
  readonly includeAssets: boolean;
}

export interface SupplementalIdentity {
  readonly section: SupplementalSectionKind;
  readonly key: string;
}

export interface SupplementalCollisionChoice extends SupplementalIdentity {
  readonly action: SupplementalCollisionAction;
}

export interface CollisionPlan {
  readonly scenarios: Readonly<Record<UuidV7, CollisionAction>>;
  readonly supplementalChoices: readonly SupplementalCollisionChoice[];
}

export interface PortableCountsDto {
  readonly scenarios: number;
  readonly scenarioRevisions: number;
  readonly results: number;
  readonly sharedRecords: number;
  readonly preferences: number;
  readonly assets: number;
}

export interface SourceBackupSelectionDto {
  readonly includeResults: boolean;
  readonly assetSelection: PortableBackupAssetSelection;
  readonly thresholdVersion: number | null;
  readonly thresholdBytes: number | null;
  readonly excludedAssetCount: number;
  readonly excludedAssetIds: readonly string[];
  readonly fixedExclusions: readonly FixedExclusion[];
  readonly scope: BackupSelectionScope;
}

export interface OmittedAssetDto {
  readonly assetId: string;
  readonly format: string;
  readonly version: number;
  readonly reason: OmittedAssetReason;
  readonly originalMediaType: string;
  readonly originalSize: number;
  readonly contentSha256: string;
}

export interface BackupSummaryDto {
  readonly includeResults: boolean;
  readonly assetSelection: PortableBackupAssetSelection;
  readonly excludedAssetCount: number;
  readonly excludedAssetIds: readonly string[];
  readonly exclusionScope: string | null;
  readonly thresholdVersion: number | null;
  readonly thresholdBytes: number | null;
  readonly fixedExclusions: readonly FixedExclusion[];
}

export interface PortableCapabilityDto {
  readonly id: string;
  readonly version: number;
}

export interface PortableScenarioDto {
  readonly scenarioId: UuidV7;
  readonly title: string;
  readonly collides: boolean;
  readonly sourceRevision: Revision;
  readonly sameIdentityRevision: Revision;
  readonly sameIdentityRevisionWarning: string | null;
}

export interface AppliedMigrationDto {
  readonly registry: "outer" | "portable";
  readonly name: string;
  readonly fromVersion: number;
  readonly toVersion: number;
}

export interface PortableSourceApplicationDto {
  readonly name: string;
  readonly version: string;
}

export interface RemovedScenarioDto {
  readonly scenarioId: UuidV7;
  readonly title: string;
  readonly revision: Revision;
  readonly archived: boolean;
}

export interface PortablePreviewDto {
  readonly previewId: UuidV7;
  readonly bundleId: UuidV7;
  readonly bundleKind: "scenario-export" | "full-backup";
  readonly title: string;
  readonly createdAt: string;
  readonly sourceApplication: PortableSourceApplicationDto;
  readonly sourceFormatVersion: number;
  readonly sourceSchemaVersion: number;
  readonly counts: PortableCountsDto;
  readonly requiredCapabilities: readonly PortableCapabilityDto[];
  readonly preservedExtensions: readonly string[];
  readonly includedSections: readonly string[];
  readonly excludedSections: readonly string[];
  readonly sourceBackupSelection: SourceBackupSelectionDto | null;
  readonly omittedAssets: readonly OmittedAssetDto[];
  readonly scenarios: readonly PortableScenarioDto[];
  readonly supplementalCollisions: readonly SupplementalIdentity[];
  readonly removedScenarios: readonly RemovedScenarioDto[];
  readonly removedSupplemental: readonly SupplementalIdentity[];
  readonly settingsChanged: readonly string[];
  readonly settingsRemoved: readonly string[];
  readonly appliedMigrations: readonly AppliedMigrationDto[];
}

export interface PortableAppliedDto {
  readonly scenarioIds: readonly UuidV7[];
}

export interface PortableFilePreviewDto {
  readonly title: string;
  readonly byteLength: number;
  readonly backupSummary: BackupSummaryDto | null;
  readonly previewId: UuidV7;
  readonly digest: string;
  readonly currentRevision: Revision | null;
  readonly libraryRevision: Revision | null;
}

export interface PortableArtifactDto {
  readonly artifactName: string;
}

export interface RestoreAuthorizationDto {
  readonly destructiveActionConfirmed: boolean;
  readonly safetyBackupBypassPhrase: string | null;
}

export type EmptyDto = Readonly<Record<string, never>>;

export interface ActorRef {
  readonly actorId: string | null;
  readonly displayName: string;
}

export type CommandSource = "desktop" | "cli" | "import" | "system" | "undo" | "redo";

export interface HistoryEntryDto {
  readonly id: UuidV7;
  readonly revisionBefore: Revision;
  readonly revisionAfter: Revision;
  readonly commandType: string;
  readonly command: JsonValue;
  readonly inverse: JsonValue;
  readonly actor: ActorRef;
  readonly source: CommandSource;
  readonly summary: string;
  readonly createdAt: string;
  readonly historySequence: number;
  readonly branchGeneration: number;
  readonly applied: boolean;
}

export interface SettingEntryDto {
  readonly value: JsonValue;
  readonly updatedAt: string;
}

export type ScenarioCommand =
  | {
      readonly type: "addEntity";
      readonly payload: { readonly entityId: UuidV7; readonly value: JsonValue };
    }
  | {
      readonly type: "updateEntity";
      readonly payload: { readonly entityId: UuidV7; readonly value: JsonValue };
    }
  | { readonly type: "removeEntity"; readonly payload: { readonly entityId: UuidV7 } }
  | {
      readonly type: "addRule";
      readonly payload: { readonly ruleId: UuidV7; readonly value: JsonValue };
    }
  | {
      readonly type: "updateRule";
      readonly payload: { readonly ruleId: UuidV7; readonly value: JsonValue };
    }
  | { readonly type: "removeRule"; readonly payload: { readonly ruleId: UuidV7 } }
  | {
      readonly type: "setPreference";
      readonly payload: { readonly preferenceId: UuidV7; readonly value: JsonValue };
    }
  | {
      readonly type: "lockAssignment";
      readonly payload: { readonly assignmentId: UuidV7; readonly value: JsonValue };
    }
  | { readonly type: "unlockAssignment"; readonly payload: { readonly assignmentId: UuidV7 } }
  | {
      readonly type: "applyDomainCommand";
      readonly payload: { readonly commandType: string; readonly payload: JsonValue };
    }
  | {
      readonly type: "applyBatch";
      readonly payload: {
        readonly label: string | null;
        readonly commands: readonly ScenarioCommand[];
      };
    };

export interface ScenarioDocumentDto {
  readonly format: "eutheto/scenario";
  readonly formatVersion: number;
  readonly scenarioId: UuidV7;
  readonly domainPack: DomainPackRef;
  readonly metadata: {
    readonly title: string;
    readonly description: string;
    readonly createdAt: string;
    readonly updatedAt: string;
  };
  readonly settings: ScenarioSettings;
  readonly domain: {
    readonly entities: Readonly<Record<UuidV7, JsonValue>>;
    readonly rules: Readonly<Record<UuidV7, JsonValue>>;
    readonly preferences: Readonly<Record<UuidV7, JsonValue>>;
    readonly lockedAssignments: Readonly<Record<UuidV7, JsonValue>>;
  };
  readonly extensions: Readonly<Record<string, JsonValue>>;
}

export interface ScenarioViewDto {
  readonly revision: Revision;
  readonly document: ScenarioDocumentDto;
  readonly validation: { readonly issues: readonly ValidationIssue[] };
}

export interface CommandResultDto {
  readonly newRevision: Revision;
  readonly changeSet: unknown;
  readonly validationDelta: unknown;
  readonly inverse: ScenarioCommand | null;
}

export type EventTopic =
  | "solve://progress"
  | "solve://completed"
  | "scenario://changed"
  | "scenario://validation-changed"
  | "counterfactual://progress"
  | "ai://stream"
  | "ai://proposal-ready"
  | "ai://completed"
  | "update://available"
  | "app://notification";

export interface EventContextDto {
  readonly eventVersion: number;
  readonly timestamp: string;
  readonly requestId: UuidV7 | null;
  readonly scenarioId: UuidV7 | null;
  readonly revision: Revision | null;
  readonly solveRunId: UuidV7 | null;
}

export type SolvePhase = "queued" | "compiling" | "solving" | "verifying" | "explaining";
export type SolveStatus =
  | "optimal"
  | "feasible"
  | "infeasible"
  | "unbounded"
  | "noSolutionWithinLimit"
  | "cancelled"
  | "invalidModel"
  | "backendUnavailable"
  | "backendFailed";

export type AppEventDto =
  | {
      readonly topic: "solve://progress";
      readonly payload: {
        readonly type: "solveProgress";
        readonly payload: {
          readonly context: EventContextDto;
          readonly phase: SolvePhase;
          readonly percent: number | null;
        };
      };
    }
  | {
      readonly topic: "solve://completed";
      readonly payload: {
        readonly type: "solveCompleted";
        readonly payload: {
          readonly context: EventContextDto;
          readonly status: SolveStatus;
          readonly solutionId: UuidV7 | null;
        };
      };
    }
  | {
      readonly topic: "scenario://changed";
      readonly payload: {
        readonly type: "scenarioChanged";
        readonly payload: { readonly context: EventContextDto; readonly changeSet: unknown };
      };
    }
  | {
      readonly topic: "scenario://validation-changed";
      readonly payload: {
        readonly type: "scenarioValidationChanged";
        readonly payload: { readonly context: EventContextDto; readonly validationDelta: unknown };
      };
    }
  | {
      readonly topic: "app://notification";
      readonly payload: {
        readonly type: "appNotification";
        readonly payload: {
          readonly context: EventContextDto;
          readonly code: string;
          readonly message: string;
        };
      };
    };

export type ScenarioChangedEvent = Extract<
  AppEventDto,
  { readonly topic: "scenario://changed" }
>["payload"];
export type ScenarioValidationChangedEvent = Extract<
  AppEventDto,
  { readonly topic: "scenario://validation-changed" }
>["payload"];
export type AppNotificationEvent = Extract<
  AppEventDto,
  { readonly topic: "app://notification" }
>["payload"];
export interface LibraryRefreshRequiredEvent {
  readonly reason: "event-subscription-lagged";
}

export function onScenarioChanged(
  listener: (event: ScenarioChangedEvent) => void,
): Promise<UnlistenFn> {
  return listen<ScenarioChangedEvent>("scenario://changed", ({ payload }) => {
    listener(payload);
  });
}

export function onScenarioValidationChanged(
  listener: (event: ScenarioValidationChangedEvent) => void,
): Promise<UnlistenFn> {
  return listen<ScenarioValidationChangedEvent>("scenario://validation-changed", ({ payload }) => {
    listener(payload);
  });
}

export function onAppNotification(
  listener: (event: AppNotificationEvent) => void,
): Promise<UnlistenFn> {
  return listen<AppNotificationEvent>("app://notification", ({ payload }) => {
    listener(payload);
  });
}
export function onLibraryRefreshRequired(
  listener: (event: LibraryRefreshRequiredEvent) => void,
): Promise<UnlistenFn> {
  return listen<LibraryRefreshRequiredEvent>("library://refresh-required", ({ payload }) => {
    listener(payload);
  });
}

__COMMAND_CATALOG__

export type CatalogCommand = (typeof COMMAND_CATALOG)[number];

function newRequestId(): UuidV7 {
  const bytes = window.crypto.getRandomValues(new Uint8Array(16));
  const timestamp = BigInt(Date.now());
  bytes[0] = Number((timestamp >> 40n) & 0xffn);
  bytes[1] = Number((timestamp >> 32n) & 0xffn);
  bytes[2] = Number((timestamp >> 24n) & 0xffn);
  bytes[3] = Number((timestamp >> 16n) & 0xffn);
  bytes[4] = Number((timestamp >> 8n) & 0xffn);
  bytes[5] = Number(timestamp & 0xffn);
  const versionByte = bytes[6];
  const variantByte = bytes[8];
  if (versionByte === undefined || variantByte === undefined) {
    throw new Error("Unable to construct request ID");
  }
  bytes[6] = (versionByte & 0x0f) | 0x70;
  bytes[8] = (variantByte & 0x3f) | 0x80;
  const hex = Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

async function call<T>(command: CatalogCommand, request: object): Promise<ApiResponseDto<T>> {
  const revision = (request as { readonly expectedRevision?: unknown }).expectedRevision;
  if (
    revision !== undefined &&
    (typeof revision !== "number" || !Number.isSafeInteger(revision) || revision < 0)
  ) {
    throw new RangeError("Revision must be a non-negative JavaScript safe integer");
  }
  return invoke<ApiResponseDto<T>>(command, { request });
}

export function getAppInfo(): Promise<ApiResponseDto<AppInfoDto>> {
  return call("app_get_info", { requestId: newRequestId() });
}

export function getAppCapabilities(): Promise<ApiResponseDto<AppCapabilitiesDto>> {
  return call("app_get_capabilities", { requestId: newRequestId() });
}

export function getAppPathsSummary(): Promise<ApiResponseDto<AppPathsSummaryDto>> {
  return call("app_get_paths_summary", { requestId: newRequestId() });
}

export function previewSupportBundle(): Promise<ApiResponseDto<SupportPreviewDto>> {
  return call("app_create_support_bundle_preview", { requestId: newRequestId() });
}
export function listDomainPacks(): Promise<ApiResponseDto<readonly DomainPackDescriptorDto[]>> {
  return call("pack_list", { requestId: newRequestId() });
}

export function describeDomainPack(packId: string): Promise<ApiResponseDto<DomainPackMetadataDto>> {
  return call("pack_describe", { requestId: newRequestId(), packId });
}

export function listSolvers(): Promise<ApiResponseDto<readonly SolverDescriptorDto[]>> {
  return call("solver_list", { requestId: newRequestId() });
}

export function describeSolver(backendId: string): Promise<ApiResponseDto<SolverDescriptorDto>> {
  return call("solver_describe", { requestId: newRequestId(), backendId });
}

export function getSolverSupportMatrix(): Promise<ApiResponseDto<SolverSupportMatrixDto>> {
  return call("solver_get_support_matrix", { requestId: newRequestId() });
}

export function getDeferredSolverGates(): Promise<
  ApiResponseDto<readonly DeferredSolverGateDto[]>
> {
  return call("solver_get_deferred_gates", { requestId: newRequestId() });
}

export function listProjects(
  scope: ProjectScope = "active",
): Promise<ApiResponseDto<readonly ProjectSummaryDto[]>> {
  return call("project_list", { requestId: newRequestId(), scope });
}

export function getProjectMetadata(
  scenarioId: UuidV7,
): Promise<ApiResponseDto<ProjectMetadataDto>> {
  return call("project_get_metadata", { requestId: newRequestId(), scenarioId });
}

export function createProject(input: {
  readonly title: string;
  readonly description: string;
  readonly domainPack: DomainPackRef;
  readonly settings: ScenarioSettings;
}): Promise<ApiResponseDto<ProjectMetadataDto>> {
  return call("project_create", { requestId: newRequestId(), ...input });
}

export function duplicateProject(input: {
  readonly sourceId: UuidV7;
  readonly expectedRevision: Revision;
  readonly title: string;
}): Promise<ApiResponseDto<ProjectMetadataDto>> {
  return call("project_duplicate", { requestId: newRequestId(), ...input });
}

export function setProjectArchived(input: {
  readonly scenarioId: UuidV7;
  readonly expectedRevision: Revision;
  readonly archived: boolean;
}): Promise<ApiResponseDto<EmptyDto>> {
  const command = input.archived ? "project_archive" : "project_unarchive";
  return call(command, {
    requestId: newRequestId(),
    scenarioId: input.scenarioId,
    expectedRevision: input.expectedRevision,
  });
}

export function deleteProject(
  scenarioId: UuidV7,
  expectedRevision: Revision,
): Promise<ApiResponseDto<EmptyDto>> {
  return call("project_delete", { requestId: newRequestId(), scenarioId, expectedRevision });
}

export function previewImport(options: ImportOptions): Promise<ApiResponseDto<PortablePreviewDto>> {
  return call("project_import_preview", { requestId: newRequestId(), options });
}

export function applyImport(input: {
  readonly previewId: UuidV7;
  readonly collisionPlan: CollisionPlan;
}): Promise<ApiResponseDto<PortableAppliedDto>> {
  return call("project_import_apply", { requestId: newRequestId(), ...input });
}

export function previewExport(scenarioId: UuidV7): Promise<ApiResponseDto<PortableFilePreviewDto>> {
  return call("project_export_preview", { requestId: newRequestId(), scenarioId });
}

export function createExport(
  scenarioId: UuidV7,
  previewId: UuidV7,
): Promise<ApiResponseDto<PortableArtifactDto>> {
  return call("project_export_create", { requestId: newRequestId(), scenarioId, previewId });
}

export function previewBackup(title: string): Promise<ApiResponseDto<PortableFilePreviewDto>> {
  return call("project_backup_preview", { requestId: newRequestId(), title });
}

export function createBackup(
  title: string,
  previewId: UuidV7,
): Promise<ApiResponseDto<PortableArtifactDto>> {
  return call("project_backup_create", { requestId: newRequestId(), title, previewId });
}

export function previewRestore(
  options: ImportOptions,
): Promise<ApiResponseDto<PortablePreviewDto>> {
  return call("project_restore_preview", { requestId: newRequestId(), options });
}

export function applyRestore(input: {
  readonly previewId: UuidV7;
  readonly collisionPlan: CollisionPlan;
  readonly authorization: RestoreAuthorizationDto;
}): Promise<ApiResponseDto<PortableAppliedDto>> {
  return call("project_restore_apply", { requestId: newRequestId(), ...input });
}

export function cancelPortablePreview(previewId: UuidV7): Promise<ApiResponseDto<EmptyDto>> {
  return call("project_operation_cancel", { requestId: newRequestId(), previewId });
}
export function inspectUnopenedBundle(): Promise<ApiResponseDto<UnopenedBundlePreviewDto>> {
  return call("project_unopened_bundle_inspect", { requestId: newRequestId() });
}

export function reexportUnopenedBundle(
  previewId: UuidV7,
): Promise<ApiResponseDto<PortableArtifactDto>> {
  return call("project_unopened_bundle_reexport", { requestId: newRequestId(), previewId });
}

export function getScenarioView(scenarioId: UuidV7): Promise<ApiResponseDto<ScenarioViewDto>> {
  return call("scenario_get_view", { requestId: newRequestId(), scenarioId });
}

export function validateScenario(
  scenarioId: UuidV7,
): Promise<ApiResponseDto<{ readonly issues: readonly ValidationIssue[] }>> {
  return call("scenario_validate", { requestId: newRequestId(), scenarioId });
}

export function applyScenarioCommand(input: {
  readonly commandId: UuidV7;
  readonly scenarioId: UuidV7;
  readonly expectedRevision: Revision;
  readonly actor: ActorRef;
  readonly command: ScenarioCommand;
  readonly truncateRedo: boolean;
}): Promise<ApiResponseDto<CommandResultDto>> {
  return call("scenario_apply_command", { requestId: newRequestId(), ...input });
}

export function applyScenarioBatch(input: {
  readonly commandId: UuidV7;
  readonly scenarioId: UuidV7;
  readonly expectedRevision: Revision;
  readonly actor: ActorRef;
  readonly label: string | null;
  readonly commands: readonly ScenarioCommand[];
  readonly truncateRedo: boolean;
}): Promise<ApiResponseDto<CommandResultDto>> {
  return call("scenario_apply_batch", { requestId: newRequestId(), ...input });
}

export function undoScenario(
  scenarioId: UuidV7,
  expectedRevision: Revision,
): Promise<ApiResponseDto<CommandResultDto>> {
  return call("scenario_undo", { requestId: newRequestId(), scenarioId, expectedRevision });
}

export function redoScenario(
  scenarioId: UuidV7,
  expectedRevision: Revision,
): Promise<ApiResponseDto<CommandResultDto>> {
  return call("scenario_redo", { requestId: newRequestId(), scenarioId, expectedRevision });
}

export function getScenarioHistory(
  scenarioId: UuidV7,
): Promise<ApiResponseDto<{ readonly entries: readonly HistoryEntryDto[] }>> {
  return call("scenario_get_history", { requestId: newRequestId(), scenarioId });
}

export function getSetting(
  key: string,
): Promise<ApiResponseDto<{ readonly setting: SettingEntryDto | null }>> {
  return call("settings_get", { requestId: newRequestId(), key });
}

export function updateSetting(key: string, value: JsonValue): Promise<ApiResponseDto<EmptyDto>> {
  return call("settings_update", { requestId: newRequestId(), key, value });
}

export function resetSettingsSection(
  key: string,
): Promise<ApiResponseDto<{ readonly existed: boolean }>> {
  return call("settings_reset_section", { requestId: newRequestId(), key });
}
"#;

fn generated_desktop_api() -> String {
    let catalog = render_typescript_command_catalog();
    DESKTOP_API_TEMPLATE.replace(TYPESCRIPT_COMMAND_CATALOG_PLACEHOLDER, &catalog)
}

fn render_typescript_command_catalog() -> String {
    let mut output = String::from("export const COMMAND_CATALOG = [\n");
    for command in COMMAND_CATALOG {
        output.push_str("  \"");
        output.push_str(command);
        output.push_str("\",\n");
    }
    output.push_str("] as const;");
    output
}

fn generated_rust_command_catalog() -> String {
    let mut output =
        String::from("// @generated by `cargo xtask generate`; do not edit by hand.\n\n");
    output.push_str("pub const REGISTERED_COMMANDS: &[&str] = &[\n");
    for command in COMMAND_CATALOG {
        output.push_str("    \"");
        output.push_str(command);
        output.push_str("\",\n");
    }
    output.push_str("];\n");
    output
}

pub fn generate(repo_root: &Path) -> Result<()> {
    let generated_files = all_generated_files(repo_root)?;
    crate::protocol_generate::remove_obsolete(repo_root, &generated_files)?;
    for (relative_path, contents) in &generated_files {
        let path = repo_root.join(relative_path);
        let parent = path
            .parent()
            .with_context(|| format!("generated path has no parent: {}", path.display()))?;
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;

        if fs::read(&path).ok().as_deref() != Some(contents.as_slice()) {
            fs::write(&path, contents)
                .with_context(|| format!("failed to write {}", path.display()))?;
        }
    }

    println!("generated {} file(s)", generated_files.len());
    Ok(())
}

pub fn check(repo_root: &Path) -> Result<()> {
    let generated_files = all_generated_files(repo_root)?;
    crate::protocol_generate::reject_unexpected(repo_root, &generated_files)?;
    let mut drifted = Vec::new();

    for (relative_path, expected) in &generated_files {
        let path = repo_root.join(relative_path);
        match fs::read(&path) {
            Ok(actual) if actual == expected.as_slice() => {}
            Ok(_) | Err(_) => drifted.push(relative_path.as_str()),
        }
    }

    if !drifted.is_empty() {
        bail!(
            "generated files are missing or stale: {}; run `cargo xtask generate`",
            drifted.join(", ")
        );
    }

    println!("checked {} generated file(s)", generated_files.len());
    Ok(())
}

fn generated_files() -> Vec<(&'static str, String)> {
    vec![
        (GENERATED_DESKTOP_API_PATH, generated_desktop_api()),
        (
            GENERATED_RUST_COMMAND_CATALOG_PATH,
            generated_rust_command_catalog(),
        ),
    ]
}

fn all_generated_files(repo_root: &Path) -> Result<Vec<crate::protocol_generate::GeneratedOutput>> {
    let mut files = generated_files()
        .into_iter()
        .map(|(path, contents)| (path.to_owned(), contents.into_bytes()))
        .collect::<Vec<_>>();
    files.extend(
        crate::phase02_generate::generated_files()?
            .into_iter()
            .map(|(path, contents)| (path.to_owned(), contents.into_bytes())),
    );
    files.push(crate::source_contract::generated_file(repo_root)?);
    files.push(crate::source_contract::dependency_sources_generated_file()?);
    files.extend(crate::protocol_generate::generated_files(repo_root)?);
    files.sort_by(|left, right| left.0.cmp(&right.0));
    ensure_unique_generated_paths(&files)?;
    Ok(files)
}

fn ensure_unique_generated_paths(
    files: &[crate::protocol_generate::GeneratedOutput],
) -> Result<()> {
    for pair in files.windows(2) {
        ensure!(
            pair[0].0 != pair[1].0,
            "generated path is owned by more than one generator: {}",
            pair[0].0
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;
    use std::fmt::Write;

    use super::{
        COMMAND_CATALOG, generated_desktop_api, generated_files, generated_rust_command_catalog,
        render_typescript_command_catalog,
    };

    const FOUNDATION_PERMISSION: &str =
        include_str!("../../apps/desktop/src-tauri/permissions/foundation-status.toml");

    #[test]
    fn generated_api_has_expected_ui_wrappers() {
        let generated_api = generated_desktop_api();
        for wrapper in [
            "listProjects",
            "createProject",
            "duplicateProject",
            "setProjectArchived",
            "deleteProject",
            "previewImport",
            "applyImport",
            "previewExport",
            "createExport",
            "previewBackup",
            "createBackup",
            "previewRestore",
            "applyRestore",
            "cancelPortablePreview",
            "onAppNotification",
            "onScenarioChanged",
            "onLibraryRefreshRequired",
            "onScenarioValidationChanged",
            "previewSupportBundle",
            "listDomainPacks",
            "describeDomainPack",
            "listSolvers",
            "describeSolver",
            "getSolverSupportMatrix",
            "getDeferredSolverGates",
            "inspectUnopenedBundle",
            "reexportUnopenedBundle",
        ] {
            assert!(generated_api.contains(&format!("function {wrapper}")));
        }
        assert!(generated_api.ends_with('\n'));
    }

    #[test]
    fn portable_wrappers_leave_native_file_selection_to_rust() {
        let generated_api = generated_desktop_api();
        for expected in [
            "function previewImport(options: ImportOptions)",
            "call(\"project_import_preview\", { requestId: newRequestId(), options })",
            "function previewRestore(\n  options: ImportOptions,\n)",
            "call(\"project_restore_preview\", { requestId: newRequestId(), options })",
            "function createBackup(\n  title: string,\n  previewId: UuidV7,\n)",
            "call(\"project_backup_create\", { requestId: newRequestId(), title, previewId })",
            "function createExport(\n  scenarioId: UuidV7,\n  previewId: UuidV7,\n)",
            "call(\"project_export_create\", { requestId: newRequestId(), scenarioId, previewId })",
            "function previewSupportBundle()",
            "call(\"app_create_support_bundle_preview\", { requestId: newRequestId() })",
            "function inspectUnopenedBundle()",
            "call(\"project_unopened_bundle_inspect\", { requestId: newRequestId() })",
            "function reexportUnopenedBundle(\n  previewId: UuidV7,\n)",
            "call(\"project_unopened_bundle_reexport\", { requestId: newRequestId(), previewId })",
        ] {
            assert!(generated_api.contains(expected), "missing `{expected}`");
        }
        assert!(!generated_api.contains("sourceArtifact"));
        assert!(!generated_api.contains("readonly fileName"));
        assert!(generated_api.contains("interface SupportPreviewDto"));
        assert!(generated_api.contains("interface UnopenedBundlePreviewDto"));
        assert!(generated_api.contains("export type SolverSupportCellDto"));
        assert!(generated_api.contains("interface SolverSupportBackendColumnDto"));
        assert!(
            generated_api
                .contains("readonly backendColumns: readonly SolverSupportBackendColumnDto[];")
        );
        assert!(!generated_api.contains("readonly bytes"));
    }

    #[test]
    fn generated_api_uses_prettier_layout() {
        let generated_api = generated_desktop_api();
        for expected in [
            "export type JsonValue =\n  null | boolean | number | string | readonly JsonValue[] | { readonly [key: string]: JsonValue };",
            "export type ScenarioCommand =\n  | {\n      readonly type: \"addEntity\";",
            "export type AppEventDto =\n  | {\n      readonly topic: \"solve://progress\";",
            "export function listProjects(\n  scope: ProjectScope = \"active\",\n): Promise<ApiResponseDto<readonly ProjectSummaryDto[]>>",
            "export function undoScenario(\n  scenarioId: UuidV7,\n  expectedRevision: Revision,\n): Promise<ApiResponseDto<CommandResultDto>>",
        ] {
            assert!(generated_api.contains(expected), "missing `{expected}`");
        }
    }

    #[test]
    fn typescript_command_catalog_has_one_entry_per_line() {
        let mut entries = String::new();
        for command in COMMAND_CATALOG {
            let _ = writeln!(entries, "  \"{command}\",");
        }
        assert_eq!(
            render_typescript_command_catalog(),
            format!("export const COMMAND_CATALOG = [\n{entries}] as const;")
        );
    }

    #[test]
    fn generated_outputs_share_the_command_catalog_authority() {
        let generated = generated_files();
        assert_eq!(generated.len(), 2);
        assert_eq!(generated[0].0, "apps/desktop/src/api/generated.ts");
        assert_eq!(
            generated[1].0,
            "apps/desktop/src-tauri/src/generated_command_catalog.rs"
        );

        let generated_api = generated_desktop_api();
        let generated_rust = generated_rust_command_catalog();
        assert_eq!(COMMAND_CATALOG.len(), 91);
        assert_eq!(
            COMMAND_CATALOG
                .iter()
                .copied()
                .collect::<BTreeSet<_>>()
                .len(),
            COMMAND_CATALOG.len()
        );
        for command in COMMAND_CATALOG {
            let quoted = format!("\"{command}\"");
            assert!(generated_api.contains(&quoted));
            assert!(generated_rust.contains(&quoted));
        }
        assert!(generated_api.contains("export const COMMAND_CATALOG"));
        assert!(generated_api.contains("export type AppEventDto"));
        assert!(!generated_api.contains("app_get_foundation_status"));
        assert!(!generated_rust.contains("app_get_foundation_status"));
    }

    #[test]
    fn foundation_permission_matches_the_command_catalog() {
        let permission_commands: Vec<_> = FOUNDATION_PERMISSION
            .lines()
            .filter_map(|line| {
                line.trim()
                    .strip_prefix('"')
                    .and_then(|line| line.strip_suffix("\","))
            })
            .collect();
        assert_eq!(permission_commands, COMMAND_CATALOG);
    }

    #[test]
    fn wrappers_keep_tauri_import_private_to_generated_api() {
        let generated_api = generated_desktop_api();
        assert_eq!(generated_api.matches("@tauri-apps/api/core").count(), 1);
        assert_eq!(generated_api.matches("function call<").count(), 1);
        assert!(generated_api.contains("invoke<ApiResponseDto<T>>(command, { request })"));
    }
}
