use std::borrow::Cow;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result, bail};
use eutheto_types::FoundationStatus;
use serde_json::Value;

const GENERATED_DESKTOP_API_PATH: &str = "apps/desktop/src/api/generated.ts";
const GENERATED_DESKTOP_API_HEADER: &str = r#"// @generated by `cargo xtask generate`; do not edit by hand.
import { invoke } from "@tauri-apps/api/core";

export interface FoundationStatus {
"#;
const GENERATED_DESKTOP_API_FOOTER: &str = r#"}

export async function getFoundationStatus(): Promise<FoundationStatus> {
  return invoke<FoundationStatus>("app_get_foundation_status");
}
"#;

pub fn generate(repo_root: &Path) -> Result<()> {
    let generated_files = generated_files()?;
    for (relative_path, contents) in &generated_files {
        let path = repo_root.join(relative_path);
        let parent = path
            .parent()
            .with_context(|| format!("generated path has no parent: {}", path.display()))?;
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;

        if fs::read_to_string(&path).ok().as_deref() != Some(contents.as_str()) {
            fs::write(&path, contents)
                .with_context(|| format!("failed to write {}", path.display()))?;
        }
    }

    println!("generated {} file(s)", generated_files.len());
    Ok(())
}

pub fn check(repo_root: &Path) -> Result<()> {
    let generated_files = generated_files()?;
    let mut drifted = Vec::new();

    for (relative_path, expected) in &generated_files {
        let path = repo_root.join(relative_path);
        match fs::read_to_string(&path) {
            Ok(actual) if actual == *expected => {}
            Ok(_) | Err(_) => drifted.push(*relative_path),
        }
    }

    if !drifted.is_empty() {
        bail!(
            "generated files are missing or stale: {}; run `cargo xtask generate`",
            drifted.join(", ")
        );
    }

    println!("checked {} generated file(s)", generated_files.len());
    Ok(())
}

fn generated_files() -> Result<[(&'static str, String); 1]> {
    Ok([(GENERATED_DESKTOP_API_PATH, generated_desktop_api()?)])
}

fn generated_desktop_api() -> Result<String> {
    let serialized = serde_json::to_value(FoundationStatus::phase_00())
        .context("failed to serialize FoundationStatus")?;
    let fields = serialized
        .as_object()
        .context("FoundationStatus must serialize as a JSON object")?;
    let mut fields = fields.iter().collect::<Vec<_>>();
    fields.sort_unstable_by_key(|(name, _)| *name);

    let mut generated = String::from(GENERATED_DESKTOP_API_HEADER);
    for (name, value) in fields {
        generated.push_str("  readonly ");
        generated.push_str(&typescript_property_name(name)?);
        generated.push_str(": ");
        generated.push_str(&typescript_literal(value)?);
        generated.push_str(";\n");
    }
    generated.push_str(GENERATED_DESKTOP_API_FOOTER);
    Ok(generated)
}

fn typescript_property_name(name: &str) -> Result<Cow<'_, str>> {
    if is_typescript_identifier(name) {
        Ok(Cow::Borrowed(name))
    } else {
        serde_json::to_string(name)
            .map(Cow::Owned)
            .context("failed to render a FoundationStatus field name")
    }
}

fn is_typescript_identifier(name: &str) -> bool {
    let mut characters = name.chars();
    characters
        .next()
        .is_some_and(|first| first.is_ascii_alphabetic() || matches!(first, '_' | '$'))
        && characters
            .all(|character| character.is_ascii_alphanumeric() || matches!(character, '_' | '$'))
}

fn typescript_literal(value: &Value) -> Result<String> {
    match value {
        Value::Null | Value::Bool(_) | Value::Number(_) | Value::String(_) => {
            serde_json::to_string(value).context("failed to render a FoundationStatus field type")
        }
        Value::Array(_) | Value::Object(_) => {
            bail!("FoundationStatus fields must serialize as scalar JSON values")
        }
    }
}

#[cfg(test)]
mod tests {
    use anyhow::{Context, Result};
    use eutheto_types::FoundationStatus;

    use super::{generated_desktop_api, typescript_literal, typescript_property_name};

    #[test]
    fn generated_api_has_one_typed_command_boundary() -> Result<()> {
        let generated = generated_desktop_api()?;
        assert_eq!(generated.matches("invoke<").count(), 1);
        assert!(generated.contains("app_get_foundation_status"));
        assert!(generated.ends_with('\n'));
        Ok(())
    }

    #[test]
    fn generated_interface_follows_serialized_foundation_status() -> Result<()> {
        let serialized = serde_json::to_value(FoundationStatus::phase_00())?;
        let fields = serialized
            .as_object()
            .context("FoundationStatus must serialize as an object")?;
        let generated = generated_desktop_api()?;

        assert_eq!(generated.matches("  readonly ").count(), fields.len());
        for (name, value) in fields {
            let field = format!(
                "  readonly {}: {};",
                typescript_property_name(name)?,
                typescript_literal(value)?
            );
            assert!(generated.contains(&field));
        }
        Ok(())
    }
}
